name: Deploy Android preview

on:
  push:
    branches: [main]
    paths:
      - apps/mobile/**
      - packages/shared/**
      - package.json
      - package-lock.json

jobs:
  fingerprint:
    name: Fingerprint Android app
    type: fingerprint
    environment: preview

  get_android_build:
    name: Find compatible Android preview
    needs: [fingerprint]
    type: get-build
    params:
      fingerprint_hash: ${{ needs.fingerprint.outputs.android_fingerprint_hash }}
      profile: preview

  build_android:
    name: Build Android preview
    needs: [get_android_build]
    if: ${{ !needs.get_android_build.outputs.build_id }}
    type: build
    params:
      platform: android
      profile: preview

  publish_android_update:
    name: Publish Android preview update
    needs: [get_android_build]
    if: ${{ needs.get_android_build.outputs.build_id }}
    type: update
    environment: preview
    params:
      channel: preview
      platform: android
